name: Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    name: Build AthenaOS
    runs-on: ubuntu-latest
    container: cbrzeszczot/wonderful:wswan-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v3

      - name: Install additional dependencies
        run: apt-get update && apt-get install -y python3 python3-pil

      - name: Build
        run: make

      - name: Archive ROM
        uses: actions/upload-artifact@v4
        with:
          name: AthenaOS
          path: dist/
